---
title: 'Data Analysis #1'
output: html_document
---



```{r}
#Loading in data from computer
df = read.csv("~/R/Personal Projects/security_incidents_2022-11-13.csv")
```

```{r}
#Original data
df
```

```{r}
#Getting rid of columns with irrelevant information
df2 = df[,-c(1, 34, 35, 41, 40, 39)]
```

```{r}
df2
```

```{r}
#potentially interesting data: which days did most events occur on, which country was the most common, difference between national and international, differences between gender, 
df_num = df2[,-c(4,5,6,7,8,30, 31, 32, 33, 34, 35)]
```

```{r}
#Getting rid of text row, redundant
df_num = df_num[-1,]
```

```{r}
#Dataframe with all relevant numerical columns
df_num
```

```{r}
#Must turn data in dataframe to numeric class, as it is currently string

i = c(1, 2, 3, 4, 5, 6, 7,8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24)
df_num[ , i] <- apply(df_num[ , i], 2,            # Specify own function within apply
                    function(x) as.numeric(as.character(x)))
```

```{r}
#Call in visualization packages

library(ggplot2)
library(reshape2)
```

```{r}
#Creating a correlational table

data = cor(df_num[sapply(df_num, is.numeric)])
data1 = melt(data)
head(data1)
```


```{r}
#Expanding table and rounding numbers

res = cor(df_num)
round(res, 2)
```

```{r}
df_num = df_num[,-c(2, 3, 6, 7, 8)]
```


# Visualizations



```{r}
#Creating a correlation plot


library(corrplot)

corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 90)
```

```{r}
#Finding out which year had the most number of incidents

tail(names(sort(table(df2$Year))), 1)


```

Most incidents happened in the year 2020. 


```{r}
#Creating histogram to show those years

hist(df_num$Year)
```
```{r}
library(ggplot2)
ggplot(df_num, aes(x=Year))+
  geom_histogram(color="darkblue", fill="lightblue")
```


```{r}
#Which country had the most number of incidents
tail(names(sort(table(df2$Country))), 1)
```

Differences between male and female incidents

```{r}
sum(df_num$Gender.Male)
```

```{r}
sum(df_num$Gender.Female)
```

```{r}
barplot(colSums(df_num))
```

```{r}
#Using ggplot to show a histogram describing male and female gender

sumdata=data.frame(value=apply(df_num,2,sum))
sumdata$key=rownames(sumdata)
ggplot(data=sumdata, aes(x=key, y=value, fill=key)) +
geom_bar(colour="black", stat="identity")
```



```{r}
i = colsums(df_num)
```

```{r}
df_num = df_num[,-c(1, 2, 3, 4, 5) ]
```


```{r}
df_num
```


